### ISSUE TITLE
Consider other project name, as git-shell means something else

### ISSUE THREAD

**Issue by nanoant** [gogits/git-module#1]
@Unknwon as I mentioned on Gitter, IMHO `git-shell` is unlucky name. While I understand your intention that you wanted use pure `git` shell command but there are few caveats:

1. This project is not a shell, it is a library (module, API, wrapper), see [definition of Shell](https://en.wikipedia.org/wiki/Shell_(computing))

2. There is already `git-shell` part of official Git project and it is something else (a real but restricted login shell in fact) see https://git-scm.com/docs/git-shell

Therefore consider renaming the project to something like `go-git-module`, `go-git-wrapper` or some other name which reflects what is the purpose of this project. This will help community to properly lookup your project and help with extending it.

**Comment by Unknwon** [comment]
I think give better README description is good enough for people to clarify what is does.

Thoughts?

**Comment by nanoant** [comment]
Like I said, this project isn't a shell, it is a go wrapper around `git` command that isn't an shell command either, it is just a command line program, not shell builtin.
Yet this project may be very useful for some others, given it has right name and right description, this is what GitHub searched first.

Giving explanation in README will clarify that to anyone coming there by mistake, looking for shell, but this won't help much finding go module or go wrapper for git.

**Comment by Unknwon** [comment]
OK... how about `gogs-shell`.

**Comment by nanoant** [comment]
Don't get me wrong, because this project is great, but why you want call `shell` something that isn't a shell according to common definition https://en.wikipedia.org/wiki/Shell_(computing)?

If you don't like `git-wrapper`, maybe `git-cmd` then?

**Comment by Unknwon** [comment]
I want to call it `git-module` but based on your argument it is also too vague ..

**Comment by nanoant** [comment]
Maybe it is vague, but at least it is what the name says :)

**Comment by Unknwon** [comment]
Cool! So... a lot rename on Gogs main repo..

**Comment by nanoant** [comment]
Luckily GitHub redirects the old name to the new name well, including git clones. https://help.github.com/articles/renaming-a-repository/

**Comment by Unknwon** [comment]
But Go import path does not redirect :joy:
